### ISSUE TITLE
Regarding training ,

### ISSUE THREAD

**Issue by narennadig** [BGU-CS-VIL/DeepMCBM#1]
Hey,
 I replaced the images in the (input/tennis/frames/) folder with the ones I have,  I have kept it for training, how long does it take?
 
 It's been 1 hr with 346 epochs now

**Comment by guy-erez** [comment]
Hello, 
It depends on the length of the movie, and the graphics card you are using. In general, the learning can be slow , partially because the current code is not optimized. Inference, however,  is fast.

**Comment by narennadig** [comment]
Thanks!

One last question,

How many Epochs for STN and BMN  do we ideally need to get good results, we have around 360 frames to train.

**Comment by guy-erez** [comment]
The amount of epochs needed depends (as in any learning task) on the complexity of the data . In this case it depends on complexity of the camera-movement. From our experiments, around ~5000 epochs for the STN and ~1000 epochs for the BMN should be fine.

**Comment by guy-erez** [comment]
I close this issue
