### ISSUE TITLE
No such file or directory: './input/tennis/GT'

### ISSUE THREAD

**Issue by piercus** [BGU-CS-VIL/DeepMCBM#3]
Hello @ronshapiraweber,

Thanks for this repo, i wanted to experiment a little bit on my side

I was trying to run `python src/DeepMCBM.py` on my side and I'm having `No such file or directory: './input/tennis/GT'`

Is there anything to do to download the groundtruths for tennis ?

Best regards

**Comment by guy-erez** [comment]
Hi @piercus,

The GT directory will shortly be available within the repo. In the meanwhile you can downlead the DAVIS 2017 dataset from [https://davischallenge.org/davis2017/code.html](https://davischallenge.org/davis2017/code.html) 

Thank you for that issue and sorry for the inconvenience.

**Comment by guy-erez** [comment]
tennis GT is available now.

**Comment by piercus** [comment]
Thanks
