### ISSUE TITLE
Training on multiple different videos

### ISSUE THREAD

**Issue by piercus** [BGU-CS-VIL/DeepMCBM#4]
Hello @ronshapiraweber,

Thanks for this repo.

Is it possible to train it on multiple different videos, in the training example, it is only using one video (input/tennis) ?

**Comment by guy-erez** [comment]
Hi @piercus,
The module is trained per sequence (tennis for example). A trained module can predict background for more frames taken from the same scene covered during training (the same tennis court for the tennis sequence).

**Comment by piercus** [comment]
Thanks for your feedback
