### ISSUE TITLE
The model trained learnt quite a lot color infor? 

### ISSUE THREAD

**Issue by AvadaKarrot** [BGU-CS-VIL/DeepMCBM#5]
I found that the background results are complete darkness while using infrared dataset. Every pixels of the results are almost 0. Maybe can't adapt to Infrared Images.

**Comment by guy-erez** [comment]
Hi, we didn't test the model for Infrared Images, but I believe it should work. I will recommend inspecting the alignment image along the training process and tune the learning rate in case of a fatal failure.

**Comment by guy-erez** [comment]
I am closing this issue.
