### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dhauis** [BGU-CS-VIL/DeepMCBM#6]
I want to train a new model, do I need to get his masking map first?

**Comment by guy-erez** [comment]
This is an unsupervised model, no labeling needed for training.

**Comment by dhauis** [comment]
![00000](https://github.com/BGU-CS-VIL/DeepMCBM/assets/130041948/2497986f-7254-4df2-921e-aa31a21a2aa6)
I don't need this picture？

**Comment by guy-erez** [comment]
Only for evaluation, training is done merely on the input images.

**Comment by dhauis** [comment]
Then I want to extract the video background of multiple people, can I just use tennis.ckpt?

**Comment by guy-erez** [comment]
no, the model should be trained per scene, if your video takes place in a different scene you should train a new model and use the new set of weights.  
I highly recommend reading the paper to better understand the idea of this background model.

**Comment by dhauis** [comment]
ok，thank

**Comment by dhauis** [comment]
When I used my new weights, I reported this error "raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BMN:", this is why

**Comment by guy-erez** [comment]
Can you please give more details to reproduce the error?
